# Purpose: Construct bootstrap confidence intervals.
# Updated: 2024-02-24

# -----------------------------------------------------------------------------
# Shared assembly of CIs and p-values from resampling (used by CompareStratAUCs and CompareAugAUCs)
# -----------------------------------------------------------------------------

#' Assemble CIs and p-values including optional bootstrap and permutation.
#'
#' @param obs_stats Data.frame of observed contrasts (contrast, observed, se, lower, upper, p).
#' @param data Formatted data.
#' @param tau Truncation time.
#' @param alpha Type I error.
#' @param boot Run bootstrap?
#' @param perm Run permutation?
#' @param reps Number of replicates.
#' @param boot_sim_fun Function(data, obs_stats, tau, alpha, reps) returning bootstrap sim data.frame with is_diff_sign.
#' @param perm_sim_fun Function(data, obs_stats, tau, alpha, reps) returning permutation sim data.frame.
#' @param format_perm_pvals Function(perm_sim, obs_stats) returning data.frame(method, contrast, observed, p).
#' @return List with cis, pvals, sim_reps.
#' @noRd
.AddResamplingResults <- function(
  obs_stats,
  data,
  tau,
  alpha,
  boot,
  perm,
  reps,
  boot_sim_fun,
  perm_sim_fun,
  format_perm_pvals
) {
  contrast <- observed <- p <- NULL
  cis <- obs_stats %>% dplyr::select(-dplyr::any_of("p"))
  cis <- data.frame(method = "asymptotic", cis)
  pvals <- obs_stats %>% dplyr::select(dplyr::any_of(c("contrast", "observed", "p")))
  pvals <- data.frame(method = "asymptotic", pvals)
  sim_reps <- list()

  if (boot) {
    boot_sim <- boot_sim_fun(data = data, obs_stats = obs_stats, tau = tau, alpha = alpha, reps = reps)
    sim_reps$boot_sim <- boot_sim
    boot_cis <- BootCIs(sim = boot_sim, obs_stats = obs_stats, alpha = alpha)
    cis <- rbind(cis, boot_cis)
    cis <- cis[order(cis$contrast), ]
    boot_p <- CalcP(boot_sim$is_diff_sign)
    boot_pvals <- data.frame(
      method = "bootstrap",
      contrast = obs_stats$contrast,
      observed = obs_stats$observed,
      p = boot_p
    )
    pvals <- rbind(pvals, boot_pvals)
  }

  if (perm) {
    perm_sim <- perm_sim_fun(data = data, obs_stats = obs_stats, tau = tau, alpha = alpha, reps = reps)
    sim_reps$perm_sim <- perm_sim
    perm_pvals <- format_perm_pvals(perm_sim, obs_stats)
    pvals <- rbind(pvals, perm_pvals)
  }

  list(cis = cis, pvals = pvals, sim_reps = sim_reps)
}

# -----------------------------------------------------------------------------

#' Bootstrap Confidence Intervals
#'
#' @param sim Bootstrap simulation results, as generated by \code{\link{BootSimStrat}}.
#' @param obs_stats Observed contrasts.
#' @param alpha Type I error.
#' @return Data.frame containing the equi-tailed and highest-density bootstrap
#'   confidence intervals.
BootCIs <- function(
  sim,
  obs_stats,
  alpha = 0.05
) {
  
  # CI for area.
  if (!is.null(sim$area)) {
    alpha2 <- alpha / 2
    ci_area <- stats::quantile(
      x = sim$area,
      probs = c(alpha2, 1 - alpha2)
    )
    names(ci_area) <- NULL
    
    # Output.
    out <- data.frame(
      method = "bootstrap",
      contrast = "A0",
      observed = obs_stats$observed[1],
      se = stats::sd(sim$area),
      lower = ci_area[1],
      upper = ci_area[2]
    ) 
    return(out)
  }
  
  # CI for difference.
  if (!is.null(sim$boot_diff)) {
    alpha2 <- alpha / 2
    ci_diff <- stats::quantile(
      x = sim$boot_diff,
      probs = c(alpha2, 1 - alpha2)
    )
    names(ci_diff) <- NULL
    
    # Output.
    out <- data.frame(
      method = "bootstrap",
      contrast = "A1-A0",
      observed = obs_stats$observed[1],
      se = stats::sd(sim$boot_diff),
      lower = ci_diff[1],
      upper = ci_diff[2]
    ) 
  }
  
  # CI for ratio.
  if (!is.null(sim$boot_ratio)) {
  
    log_ratios <- log(sim$boot_ratio)
    finite_log_ratios <- log_ratios[is.finite(log_ratios)]
    ci_ratio <- stats::quantile(
      x = finite_log_ratios,
      probs = c(alpha2, 1 - alpha2)
    )
    names(ci_ratio) <- NULL
    ci_ratio <- exp(ci_ratio)
    se_ratio <- exp(mean(finite_log_ratios)) * stats::sd(finite_log_ratios)
    
    # Output
    out_ratio <- data.frame(
      method = "bootstrap",
      contrast = "A1/A0",
      observed = obs_stats$observed[2],
      se = se_ratio,
      lower = ci_ratio[1],
      upper = ci_ratio[2]
    )
    out <- rbind(out, out_ratio)
  }
  
  return(out)
}
