# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate AUC Influence Function Contributions 
#'
#' @param event_rate Event rate. 
#' @param idx Unique subject index. 
#' @param haz Hazard.
#' @param nar Number at risk.
#' @param status Status indicator for a single subject.
#' @param surv Survival. 
#' @param time Observation times for a single subject.
#' @return Numeric variance.
#' @noRd 
PsiAUC <- function(event_rate, idx, haz, nar, status, surv, tau, time) {
    .Call(`_MCC_PsiAUC`, event_rate, idx, haz, nar, status, surv, tau, time)
}

#' Calculate Augmentation Components
#'
#' @param covars One row per subject.
#' @param mu Grand mean.
#' @param psi Influence functions.
#' @return List.
#' @noRd 
CalcAugComp <- function(covars, mu, psi) {
    .Call(`_MCC_CalcAugComp`, covars, mu, psi)
}

#' Simulate Data for Multiple Subjects
#' 
#' @param censoring_rate Rate of censoring. 
#' @param death_rate Rate of terminal events. 
#' @param idx Subject index.
#' @param event_rate Rate of events.
#' @param tau Truncation time.
#' @return Recurrent event data for a single subject.
SimDataCpp <- function(censoring_rate, death_rate, idx, event_rate, tau) {
    .Call(`_MCC_SimDataCpp`, censoring_rate, death_rate, idx, event_rate, tau)
}

#' Calculate Mean Cumulative Function
#' 
#' Tabulates the mean cumulative function. See equation 2.1 of 
#'  <doi:10.1111/j.0006-341X.2000.00554.x>.
#'  
#' @param idx Unique subject index. 
#' @param status Status, coded as 0 for censoring, 1 for event, 2 for death. 
#' @param time Observation time.
#' @param calc_var Calculate variance of the MCF?
#' @return Data.frame with these columns:
#' \itemize{
#'    \item `times`, distinct observation times.
#'    \item `censor`, number of censorings.
#'    \item `death`, number of deaths.
#'    \item `event`, number of events.
#'    \item `haz`, instantaneous hazard (of death).
#'    \item `surv`, survival probability.
#'    \item `event_rate`, instantaneous event rate.
#'    \item `mcf`, mean cumulative function. 
#'    \item `se_mcf`, standard error of the MCF.
#' }
#' @export 
CalcMCF <- function(idx, status, time, calc_var = TRUE) {
    .Call(`_MCC_CalcMCF`, idx, status, time, calc_var)
}

